#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VitaMote.Resource", IsApplication=true)]

namespace VitaMote
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aLd = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aLl = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aLr = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int aLu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int aRd = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int aRl = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int aRr = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int aRu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bC = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bD = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bL = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bLe = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bR = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bRi = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bS = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bSe = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bSt = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bT = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bU = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bX = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int colorbg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int MyButton = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int btnIME = 2131099658;
			
			// aapt resource value: 0x7f060022
			public const int btnLoad = 2131099682;
			
			// aapt resource value: 0x7f06000b
			public const int btnMap = 2131099659;
			
			// aapt resource value: 0x7f060037
			public const int btnSve = 2131099703;
			
			// aapt resource value: 0x7f060001
			public const int editText1 = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int gridLayout1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageView1 = 2131099662;
			
			// aapt resource value: 0x7f060017
			public const int imageView10 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int imageView11 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int imageView12 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int imageView13 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int imageView14 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int imageView15 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int imageView16 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int imageView17 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int imageView18 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int imageView19 = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int imageView2 = 2131099663;
			
			// aapt resource value: 0x7f060021
			public const int imageView20 = 2131099681;
			
			// aapt resource value: 0x7f060010
			public const int imageView3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int imageView4 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int imageView5 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int imageView6 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int imageView7 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int imageView8 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int imageView9 = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int keyboard = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int scrollView1 = 2131099660;
			
			// aapt resource value: 0x7f060023
			public const int spinner1 = 2131099683;
			
			// aapt resource value: 0x7f06002c
			public const int spinner10 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int spinner11 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int spinner12 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int spinner13 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int spinner14 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int spinner15 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int spinner16 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int spinner17 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int spinner18 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int spinner19 = 2131099701;
			
			// aapt resource value: 0x7f060024
			public const int spinner2 = 2131099684;
			
			// aapt resource value: 0x7f060036
			public const int spinner20 = 2131099702;
			
			// aapt resource value: 0x7f060025
			public const int spinner3 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int spinner4 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int spinner5 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int spinner6 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int spinner7 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int spinner8 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int spinner9 = 2131099691;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int textView3 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textView5 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int textView6 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int textView7 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int keyboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Mapping = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int preview = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int rem_ime = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int subtype_en_US = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int method = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int qwerty = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
